// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("spaneventstolog")
	ScopeName = "github.com/henrikrexed/spanEventstoLog"
)

const (
	TracesToLogsStability = component.StabilityLevelBeta
)
